"""Write golf/courses/index.js from what has been built.

Cog Hill No. 4 (the original, hand-checked model) stays first; then every
course in courses/built.json, in the order courses.json lists them, with the
display names and blurbs from courses.json and the tee sets read from the
course file itself.
"""
import json, os
D = os.path.dirname(os.path.abspath(__file__))
G = os.path.join(D, '..', 'golf', 'courses')

def load(path):
    s = open(path, encoding='utf-8').read()
    return json.loads(s[s.index('{'):s.rindex('}') + 1])

def tees(C):
    names = [t['name'] for t in C['holes'][0]['tees']]
    out = []
    for i, n in enumerate(names):
        tot = sum((h['tees'][i] if i < len(h['tees']) else h['tees'][-1])['yards'] for h in C['holes'])
        out.append(dict(name=n, yards=tot))
    return out

idx = open(os.path.join(G, 'index.js'), encoding='utf-8').read()
cur = json.loads(idx[idx.index('['):idx.rindex(']') + 1])
first = [c for c in cur if c['id'] == 'cog-hill-4']
cfg = {c['id']: c for c in json.load(open(os.path.join(D, 'courses.json'), encoding='utf-8'))}
built = {b['id']: b for b in json.load(open(os.path.join(G, 'built.json'), encoding='utf-8'))}
entries = []
for cid in cfg:
    if cid not in built or not os.path.exists(os.path.join(G, cid + '.js')): continue
    c, b = cfg[cid], built[cid]
    C = load(os.path.join(G, cid + '.js'))
    entries.append(dict(id=cid, name=c['name'], sub=c['sub'], file='courses/%s.js' % cid,
                        club=c['club'], course=c['course'], city=c['city'],
                        par=C['meta']['par'], yards=C['meta']['yards'], holes=len(C['holes']),
                        tz=c.get('tz', -5), blurb=c.get('blurb', ''), tees=tees(C), lidar=True))
with open(os.path.join(G, 'index.js'), 'w', encoding='utf-8') as f:
    f.write('/* The courses the app can play. Generated by tools/update_index.py from\n'
            '   courses/built.json and tools/courses.json; Cog Hill No. 4 is the original model. */\n')
    f.write('window.COURSES = ' + json.dumps(first + entries, indent=1, ensure_ascii=False) + ';\n')
print('index:', [e['id'] for e in first + entries])
