/* The courses the app can play. Generated by tools/update_index.py from
   courses/built.json and tools/courses.json; Cog Hill No. 4 is the original model. */
window.COURSES = [
 {
  "id": "cog-hill-4",
  "name": "Dubsdread",
  "sub": "Cog Hill No. 4",
  "file": "courses/cog-hill-4.js",
  "club": "Cog Hill Golf & Country Club",
  "course": "No. 4 — Dubsdread",
  "city": "Lemont, Illinois",
  "par": 72,
  "yards": 7472,
  "holes": 18,
  "tz": -5,
  "rating": 76.6,
  "slope": 151,
  "blurb": "Dick Wilson's 1964 championship course, a four-time Western Open host: tree-lined, heavily bunkered, and long.",
  "tees": [
   {
    "name": "Dubsdread",
    "yards": 7472
   },
   {
    "name": "Championship",
    "yards": 7161
   },
   {
    "name": "Blue",
    "yards": 6690
   },
   {
    "name": "White",
    "yards": 6279
   },
   {
    "name": "Gold",
    "yards": 5857
   }
  ]
 },
 {
  "id": "pebble-beach",
  "name": "Pebble Beach Golf Links",
  "sub": "Pebble Beach Resorts",
  "file": "courses/pebble-beach.js",
  "club": "Pebble Beach Golf Links",
  "course": "Pebble Beach Golf Links",
  "city": "Pebble Beach, California",
  "par": 72,
  "yards": 6956,
  "holes": 18,
  "tz": -7,
  "blurb": "Jack Neville and Douglas Grant’s 1919 links on the cliffs above Carmel Bay — the small greens of the 7th and the long 18th along the shore.",
  "tees": [
   {
    "name": "Championship",
    "yards": 6956
   },
   {
    "name": "Back",
    "yards": 6404
   },
   {
    "name": "Middle",
    "yards": 6015
   }
  ],
  "lidar": true
 },
 {
  "id": "spyglass-hill",
  "name": "Spyglass Hill",
  "sub": "Pebble Beach Resorts",
  "file": "courses/spyglass-hill.js",
  "club": "Spyglass Hill Golf Course",
  "course": "Spyglass Hill",
  "city": "Pebble Beach, California",
  "par": 72,
  "yards": 6824,
  "holes": 18,
  "tz": -7,
  "blurb": "Robert Trent Jones Sr., 1966: five holes in the sand dunes by the ocean, then up into the Del Monte Forest.",
  "tees": [
   {
    "name": "Championship",
    "yards": 6824
   },
   {
    "name": "Back",
    "yards": 6225
   },
   {
    "name": "Middle",
    "yards": 5604
   },
   {
    "name": "Forward",
    "yards": 5435
   },
   {
    "name": "Front",
    "yards": 5364
   }
  ],
  "lidar": true
 },
 {
  "id": "torrey-pines-south",
  "name": "Torrey Pines South",
  "sub": "Torrey Pines Golf Course",
  "file": "courses/torrey-pines-south.js",
  "club": "Torrey Pines Golf Course",
  "course": "South Course",
  "city": "La Jolla, California",
  "par": 72,
  "yards": 7735,
  "holes": 18,
  "tz": -7,
  "blurb": "The city of San Diego’s clifftop course above the Pacific, a U.S. Open venue.",
  "tees": [
   {
    "name": "Championship",
    "yards": 7735
   },
   {
    "name": "Back",
    "yards": 7273
   },
   {
    "name": "Middle",
    "yards": 6530
   }
  ],
  "lidar": true
 },
 {
  "id": "chambers-bay",
  "name": "Chambers Bay",
  "sub": "Pierce County",
  "file": "courses/chambers-bay.js",
  "club": "Chambers Bay",
  "course": "Chambers Bay",
  "city": "University Place, Washington",
  "par": 72,
  "yards": 7542,
  "holes": 18,
  "tz": -7,
  "blurb": "A fescue links in a former sand-and-gravel quarry on Puget Sound, by Robert Trent Jones Jr.",
  "tees": [
   {
    "name": "Championship",
    "yards": 7542
   },
   {
    "name": "Back",
    "yards": 6840
   },
   {
    "name": "Middle",
    "yards": 6502
   }
  ],
  "lidar": true
 },
 {
  "id": "whistling-straits",
  "name": "Whistling Straits",
  "sub": "The Straits Course",
  "file": "courses/whistling-straits.js",
  "club": "Whistling Straits",
  "course": "The Straits Course",
  "city": "Haven, Wisconsin",
  "par": 72,
  "yards": 7347,
  "holes": 18,
  "tz": -5,
  "blurb": "Pete Dye’s shaped links along two miles of Lake Michigan shoreline, with bunkers beyond counting.",
  "tees": [
   {
    "name": "Championship",
    "yards": 7347
   },
   {
    "name": "Back",
    "yards": 6726
   },
   {
    "name": "Middle",
    "yards": 6305
   }
  ],
  "lidar": true
 },
 {
  "id": "harbour-town",
  "name": "Harbour Town Golf Links",
  "sub": "Sea Pines Resort",
  "file": "courses/harbour-town.js",
  "club": "Sea Pines Resort",
  "course": "Harbour Town Golf Links",
  "city": "Hilton Head Island, South Carolina",
  "par": 71,
  "yards": 6592,
  "holes": 18,
  "tz": -4,
  "blurb": "Pete Dye and Jack Nicklaus, 1969: tight, tree-lined, and finishing at the lighthouse.",
  "tees": [
   {
    "name": "Championship",
    "yards": 6592
   },
   {
    "name": "Back",
    "yards": 5966
   }
  ],
  "lidar": true
 },
 {
  "id": "kiawah-ocean",
  "name": "The Ocean Course",
  "sub": "Kiawah Island Golf Resort",
  "file": "courses/kiawah-ocean.js",
  "club": "Kiawah Island Golf Resort",
  "course": "The Ocean Course",
  "city": "Kiawah Island, South Carolina",
  "par": 72,
  "yards": 7406,
  "holes": 18,
  "tz": -4,
  "blurb": "Pete Dye’s course in the dunes along the Atlantic, exposed to the wind on every hole.",
  "tees": [
   {
    "name": "Championship",
    "yards": 7406
   },
   {
    "name": "Back",
    "yards": 6459
   }
  ],
  "lidar": true
 },
 {
  "id": "erin-hills",
  "name": "Erin Hills",
  "sub": "Erin Hills",
  "file": "courses/erin-hills.js",
  "club": "Erin Hills",
  "course": "Erin Hills",
  "city": "Erin, Wisconsin",
  "par": 72,
  "yards": 7646,
  "holes": 18,
  "tz": -5,
  "blurb": "Glacial hills and fescue in the Kettle Moraine, a U.S. Open venue.",
  "tees": [
   {
    "name": "Championship",
    "yards": 7646
   }
  ],
  "lidar": true
 },
 {
  "id": "cog-hill-2",
  "name": "Cog Hill No. 2",
  "sub": "Cog Hill Golf & Country Club",
  "file": "courses/cog-hill-2.js",
  "club": "Cog Hill Golf & Country Club",
  "course": "No. 2 — Ravines",
  "city": "Lemont, Illinois",
  "par": 72,
  "yards": 6548,
  "holes": 18,
  "tz": -5,
  "blurb": "The Ravines: Dubsdread’s neighbour, shorter and rolling.",
  "tees": [
   {
    "name": "Championship",
    "yards": 6548
   },
   {
    "name": "Back",
    "yards": 6013
   },
   {
    "name": "Middle",
    "yards": 5773
   },
   {
    "name": "Forward",
    "yards": 5672
   },
   {
    "name": "Front",
    "yards": 5638
   },
   {
    "name": "Junior",
    "yards": 5588
   }
  ],
  "lidar": true
 }
];
